ADD: Extracting synchronous generator reactive power curve from CGMES…
JakobKirschner/pandapower pull request #2
Opened 2024-12-06 10:57 UTC by Ghanshyam-grid

… data and adding gen characteristics table in net and add columnd id_characteristics in gen

2024-12-06 11:08 UTC, JakobKirschner commented on pandapower/converter/cim/cim2pp/converter_classes/generators/synchronousMachinesCim16.py
> +        if 'id_characteristic_table' not in syn_gen_df_origin.columns:
If this column is referring to the gen_capability_curve_table can we maybe rename it to e.g. "id_capability_curve_table"?

2024-12-06 11:10 UTC, JakobKirschner commented on pandapower/converter/cim/cim_classes.py
> +                    'rdfId', 'name', 'description', 'GeneratingUnit', 'EquipmentContainer', 'ratedU', 'ratedS', 'type', 'InitialReactiveCapabilityCurve',
Please also add for cim100 data structure.

2024-12-06 14:41 UTC, hilbrich commented
Hey, is the capability curve only for synchronous generators, or also relevant for static generators?

2024-12-19 07:43 UTC, Ghanshyam-grid commented
> Hey, is the capability curve only for synchronous generators, or also relevant for static generators?

This is lso relevant for static generator as well.

2025-02-24 13:12 UTC, panos-xenos requested changes
@Ghanshyam-grid, many thanks for your hard work! Please see my comments on your PR. In addition, I ran all pytests on your branch and it looks like test_all_currents_with_oos_elements is failing, whereas it is passing in the develop branch. Can you please investigate?

cc: @hilbrich @JakobKirschner @mrifraunhofer @Fabsit

2025-02-24 13:12 UTC, panos-xenos commented on CHANGELOG.rst
> +- [ADDED] add function to determine qmin and qmax from based on current active power in build_gen and update the dataframe with the determined values
@Ghanshyam-grid something wrong with syntax here ("from based on") - please review

2025-02-24 13:12 UTC, panos-xenos commented on doc/elements/gen.rst
> +----------------------------
@Ghanshyam-grid please use equal sign instead of dashes to be consistent with the rest of the document

2025-02-24 13:12 UTC, panos-xenos commented on doc/elements/gen.rst
> +of the active power output of the respective generator. This table is either auto-generated from version 3.1 onwards
from version 3.1 onwards
Please remove this text - we don't know the exact version number and we will end up forgetting to update it. Not necessary to include here.

2025-02-24 13:12 UTC, panos-xenos commented on doc/elements/gen.rst
> +    - curve_dependency_table has to be set to True, and id_q_capability_curve_table and curve_style variables need to
is curve_style parameter actually used somewhere or is it for information only? If it's for info only, then curve_style does not necessarily need to be populated, right?

2025-02-24 13:12 UTC, panos-xenos commented on doc/elements/gen.rst
> +      "constantYValue" and "straightLineYValues".
is this used for creating characteristics or somewhere else? Can someone create a new characteristic and use whatever string they want for curve_style? Does it have to be these two strings specifically?

2025-02-24 13:12 UTC, panos-xenos commented on doc/elements/gen_par.csv
> +curve_style;string;;The curve style of the generator"
remove quotes from the end (").
I would maybe rename as "The style of the generator reactive power capability curve"

2025-02-24 13:12 UTC, panos-xenos commented on doc/elements/gen_par.csv
> +curve_style;string;;The curve style of the generator"
linked to my comments above, if only two strings are allowed for curve_style, please add them in the "value range" column.

2025-02-24 13:12 UTC, panos-xenos commented on doc/elements/sgen.rst
> +----------------------------
as for gens, please use =

2025-02-24 13:12 UTC, panos-xenos commented on doc/elements/sgen.rst
> +their active power output. This table can be either automatically generated (from version 3.1 onwards) via the CIM CGMES
(from version 3.1 onwards)
please remove - we don't know the exact version number

2025-02-24 13:12 UTC, panos-xenos commented on doc/elements/sgen.rst
> +    - curve_dependency_table has to be set to True, and id_q_capability_curve_table and curve_style variables need to
same as for gens, does curve_style need to be populated?

2025-02-24 13:12 UTC, panos-xenos commented on doc/elements/sgen.rst
> +      "constantYValue" and "straightLineYValues".
same as for gens - are these two types only supported or is it just CGMES info-related only?

2025-02-24 13:12 UTC, panos-xenos commented on doc/elements/sgen_par.csv
> +curve_style;string;;The curve style of the static generator"
remove quotes from the end (").
I would maybe rename as "The style of the static generator reactive power capability curve"

2025-02-24 13:12 UTC, panos-xenos commented on doc/elements/sgen_par.csv
> +curve_style;string;;The curve style of the static generator"
linked to my comments above, if only two strings are allowed for curve_style, please add them in the "value range" column

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/build_gen.py
> +    datatype will be floated afterwards.
datatype is float right? I don't think this needs to be changed.

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/build_gen.py
> +    #Add qmin and qmax limit from q capability_curve_characteristics_table
PEP8 improvement: space after #

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/build_gen.py
> +        _calculate_qmin_qmax_from_q_capability_curve_characteristics(net,"gen")
A more generic question: I know you've implemented your changes for gen and sgen elements, but could ext_grid elements also have capability curve data?

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/build_gen.py
> +                          f"Please give gen or sgen as a argument of the function")
an argument

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/build_gen.py
> +        raise UserWarning(f"The given element type is not valid for q_min and Q_max of the {element}. "
q_max

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/build_gen.py
> +        logger.warning(f"No of {element} is zero.")
(f"No of {element} elements is zero.")

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/build_gen.py
> +        raise UserWarning(f"One of {element}(s) id characteristic(s) or curve "
I don't understand this userwarning. This is basically if len(element_data) == 0, right?

2025-02-24 13:12 UTC, panos-xenos commented on doc/elements/sgen.rst
> +Table of Static Generator Reactive Power Capability Curve Characteristics
I would suggest we move this section above electric model

2025-02-24 13:12 UTC, panos-xenos commented on doc/elements/gen.rst
> +Table of Generator Reactive Power Capability Curve Characteristics
I would suggest we move this section above electric model

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/build_gen.py
> +                              f"characteristic(s) value(s) is(are) None.")
what does that mean? What do you mean the relevant characteristic values are None? How can this happen? Maybe we need to be a bit more specific?

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/build_gen.py
> +        net[element].loc[element_data.index, ['max_q_mvar', 'min_q_mvar']] = np.column_stack((calc_q_max, calc_q_min))
Do we want to do that? This way we will be losing the original/default q_max, q_min parameters, right?

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/build_gen.py
> +                              f"characteristic(s) value(s) is(are) None.")
what happens if the p_mw value is outside the original value range from the lookup table? Does it extrapolate the q values based on the curve style somehow?

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/build_gen.py
> +                          f"style(s) of {element}(s) is(are) incorrect or not available even if the q_capability_curve_table is available.")
I understand the attempt to capture case when you have one or more of these elements, but the way this sentence is written now (e.g. is(are)) is a bit confusing to be honest.

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/control/util/auxiliary.py
> +                      f"Please give gen or sgen as a argument of the function")
an argument

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/control/util/auxiliary.py
> +            not {"id_q_capability_curve_table", "curve_dependency_table", "curve_style"}.issubset(net[element].columns)
is curve_style compulsory?

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/control/util/auxiliary.py
> +        if "q_capability_curve_characteristic" not in net.keys():
can this be False given the code in row 407?

2025-02-24 13:12 UTC, panos-xenos commented on doc/elements/gen.rst
> +column in net.q_capability_curve_table, associating each generator with its respective capability curve.
since the spline characteristic objects are required to use the capability curves, should the gen/sgen table not reflect that association, and not with the q_capability_curve_table? So, id_q_capability_curve_characteristic --> q_capability_curve_characteristic instead of id_q_capability_curve_table --> q_capability_curve_table. This should reflect how we convert things and define parameters in CGMES.

2025-02-24 13:12 UTC, panos-xenos commented on doc/elements/gen.rst
> +pandapower.control.util.auxiliary.create_q_capability_curve_characteristics_object can be utilized to automatically
if this is indeed a definite requirement to run a load flow, then we may need to re-structure the documentation to mention that this is required. If a table is given e.g. through CGMES data, then the user can use this function to create the spline characteristics.

2025-02-24 13:12 UTC, panos-xenos commented on doc/elements/sgen.rst
> +in net.q_capability_curve_table, thereby associating each static generator with its corresponding capability curve.
since the spline characteristic objects are required to use the capability curves, should the gen/sgen table not reflect that association, and not with the q_capability_curve_table? So, id_q_capability_curve_characteristic --> q_capability_curve_characteristic instead of id_q_capability_curve_table --> q_capability_curve_table. This should reflect how we convert things and define parameters in CGMES.

2025-02-24 13:12 UTC, panos-xenos commented on doc/elements/sgen.rst
> +pandapower.control.util.auxiliary.create_q_capability_curve_characteristics_object can be utilized to automatically
if this is indeed a definite requirement to run a load flow, then we may need to re-structure the documentation to mention that this is required. If a table is given e.g. through CGMES data, then the user can use this function to create the spline characteristics.

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/control/util/diagnostic.py
> +    if element not in ["gen", "sgen"]:
reminder here to check for ext_grid elements, per my comment above

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/control/util/diagnostic.py
> +def q_capability_curve_table_diagnostic(net, element):
should we rename/re-purpose this function a bit per my comment above? In this case, the table is not the requirement, the spline characteristics are. We can check in this function if there is a table but that alone does not mean that you have everything you need, right?

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/control/util/diagnostic.py
> +            not {"id_q_capability_curve_table", "curve_dependency_table", "curve_style"}.issubset(net[element].columns)
is curve_style required?

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/control/util/diagnostic.py
> +    # of q_capability_curve_table
we need to check q_capability_curve_characteristic, either in the same or a separate function. I think it makes sense to have 1 function.

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/converter/cim/cim2pp/converter_classes/generators/synchronousMachinesCim16.py
> +                syn_gen_df_origin['curve_dependency_table'] = False
is this correct? You apply False everywhere here?

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/create.py
> +        **curve_dependency_table** (bool, NaN) - True if both the id_q_capability_curve_table and the curve style\
default is False right?

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/create.py
> +        net.q_capability_curve_table
reminder to update in case we want to link to characteristics

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/create.py
> +        constant as the active power changes or varies dynamically in response to it.
Add possible input strings?

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/create.py
> +        **curve_dependency_table** (bool, NaN) - True if both the id_q_capability_curve_table and the curve style\
as above

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/create.py
> +        **curve_dependency_table** (bool, NaN) - True if both the id_q_capability_curve_table and the curve style\
this should be list of bool, because you are supposed to be creating multiple sgens? - please confirm

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/create.py
> +        **id_q_capability_curve_table** (int, None) - references the index of the characteristic from the lookup table \
list of ints

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/create.py
> +        **curve_style** (string, None) - The curve style of the generator represents the relationship \
list of strings

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/create.py
> +               "curve_style":curve_style}
PEP8: space after :

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/create.py
> +    _add_to_entries_if_not_nan(net, "gen", entries, index, "id_q_capability_curve_table",
sgen?

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/create.py
> +        **curve_dependency_table** (bool, NaN) - True if both the id_q_capability_curve_table and the curve style\
default False?

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/create.py
> +        **id_q_capability_curve_table** (int, None) - references the index of the characteristic from the lookup table \
reminder to update in case we want to link to characteristics

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/create.py
> +        **curve_style** (string, None) - The curve style of the generator represents the relationship \
add possible inputs?

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/create.py
> +
all these inputs should be lists for multiple gens

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/create.py
> +               "slack": slack, "curve_style":curve_style, "curve_dependency_table":curve_dependency_table}
PEP8: space after :

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/create.py
> +
not required

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/test/api/test_auxiliary.py
> +         'q_min_mvar':[-100.0, -75.0, -50.0, -25.0, -10], 'q_max_mvar':[150.0, 125.0, 75, 50.0, 10.0]})
PEP8: space after :

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/test/api/test_create.py
> +    assert all(net.sgen.id_q_capability_curve_table.values == [0,1,2])
PEP8: spaces after ,

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/test/api/test_create.py
> +    assert all(net.gen.id_q_capability_curve_table.values == [0,1,2])
please check in general for PEP8 improvements :)

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/test/loadflow/test_runpp.py
> +def test_net_for_q_capability_curve():
make this an internal/hidden function?

2025-02-24 13:12 UTC, panos-xenos commented on pandapower/control/util/auxiliary.py
> +def create_q_capability_curve_characteristics_object(net):
we should consider calling this function inside the cgmes converter before completing the conversion to pandapower. Without the spline characteristics, the table alone does nothing, it's not really used anywhere, right? I think it should be part of the CGMES converter to a) extract lookup from EQ profile and then b) create spline characteristics by default. For trafos and shunts we only work with the lookup table. Let's discuss on the way forward!

2025-02-24 13:16 UTC, panos-xenos commented
@Ghanshyam-grid, we should also check how we can create a PR directly into the develop, independent of the already merged shunt-characteristics branch.

2025-02-25 12:51 UTC, Ghanshyam-grid commented on doc/elements/gen.rst
> +----------------------------
done

2025-02-25 12:53 UTC, Ghanshyam-grid commented on doc/elements/gen.rst
> +of the active power output of the respective generator. This table is either auto-generated from version 3.1 onwards
Done

2025-02-25 13:22 UTC, Ghanshyam-grid commented on doc/elements/gen.rst
> +    - curve_dependency_table has to be set to True, and id_q_capability_curve_table and curve_style variables need to
it is used during the set the flag of curve_dependency_table. because we have two different types of characteristics: "straightLineYValues" and "constantYValue" so if during the data process if the curve style would be changed then the flag will not be set.

2025-02-25 13:30 UTC, Ghanshyam-grid commented on doc/elements/gen.rst
> +      "constantYValue" and "straightLineYValues".
1. Yes, it is used for creating characteristics.
2. No, there are only two characteristics. If any other string is set, then the characteristic will not be considered, and the flag of curve_dependency_table will not be set.
3. Right now, we have only these two types of curve_style specifically in CGMES.

2025-02-25 13:39 UTC, Ghanshyam-grid commented on doc/elements/sgen.rst
> +their active power output. This table can be either automatically generated (from version 3.1 onwards) via the CIM CGMES
Done

2025-02-25 13:39 UTC, Ghanshyam-grid commented on doc/elements/sgen.rst
> +    - curve_dependency_table has to be set to True, and id_q_capability_curve_table and curve_style variables need to
yes

2025-02-25 13:39 UTC, Ghanshyam-grid commented on doc/elements/sgen.rst
> +      "constantYValue" and "straightLineYValues".
yes

2025-02-25 13:40 UTC, Ghanshyam-grid commented on doc/elements/sgen_par.csv
> +curve_style;string;;The curve style of the static generator"
Done

2025-02-25 13:41 UTC, Ghanshyam-grid commented on doc/elements/sgen_par.csv
> +curve_style;string;;The curve style of the static generator"
Done

2025-02-25 13:55 UTC, Ghanshyam-grid commented on pandapower/build_gen.py
> +        raise UserWarning(f"One of {element}(s) id characteristic(s) or curve "
this warning is about the q_capability_curve_table and q_capability_curve_characteristic both are available but the curve_style or id_q_capability_curve_table are not linked to any generator.

2025-02-25 14:09 UTC, Ghanshyam-grid commented on pandapower/build_gen.py
> +                              f"characteristic(s) value(s) is(are) None.")
If the characteristic values are None, then the determined qmin and qmax are also None. If they are None, then the load flow limits for qmin and qmax are also infinite, even if the curve_dependency_table is true. this is possible if the input data is incorrect.

2025-02-25 14:14 UTC, Ghanshyam-grid commented on pandapower/build_gen.py
> +        net[element].loc[element_data.index, ['max_q_mvar', 'min_q_mvar']] = np.column_stack((calc_q_max, calc_q_min))
we have to do that because in the load flow those value are considered.

2025-02-25 14:22 UTC, Ghanshyam-grid commented on pandapower/build_gen.py
> +                              f"characteristic(s) value(s) is(are) None.")
It still gives the qmin and qmax value based on the maximum p. but i thinks this checking of p value range should be done before this stage. what do you think?

2025-02-25 14:25 UTC, Ghanshyam-grid commented on pandapower/build_gen.py
> +                          f"style(s) of {element}(s) is(are) incorrect or not available even if the q_capability_curve_table is available.")
Yes, I agree with you. However, if it is not written this way, then the user may become confused after fixing one profile of the element. what is your opinion?

2025-02-25 14:29 UTC, Ghanshyam-grid commented on pandapower/control/util/auxiliary.py
> +            not {"id_q_capability_curve_table", "curve_dependency_table", "curve_style"}.issubset(net[element].columns)
Yes, if the curve_style is unknown, then our mathematical approach of linear interpolation is incorrect.

2025-02-26 11:54 UTC, Ghanshyam-grid commented on doc/elements/gen.rst
> +column in net.q_capability_curve_table, associating each generator with its respective capability curve.
I changed only the column name in gen and sgen from id_q_capability_curve_table to id_q_capability_curve_characteristic, because I already have a dataframe with same name called q_capability_curve_characteristic.

2025-02-26 14:00 UTC, Ghanshyam-grid commented on CHANGELOG.rst
> +- [ADDED] add function to determine qmin and qmax from based on current active power in build_gen and update the dataframe with the determined values
DONE

2025-02-26 15:43 UTC, Ghanshyam-grid commented on pandapower/create.py
> +
Do you mean _set_multiple_entries?

2025-02-26 16:18 UTC, panos-xenos commented on doc/elements/gen.rst
> +      "constantYValue" and "straightLineYValues".
ok, it's interesting to see how PowerFactory treats the curve style and how we will be able to import capability curves from PowerFactory if a curve_style is not specified. Food for thought

2025-02-26 16:24 UTC, panos-xenos commented on doc/elements/sgen.rst
> +      "constantYValue" and "straightLineYValues".
you might want to say that these two curve styles "as defined in the Equipment Reliability Profile Specification". You can also provide a url link.

2025-02-26 16:36 UTC, Ghanshyam-grid commented on pandapower/create.py
> +        **curve_dependency_table** (bool, NaN) - True if both the id_q_capability_curve_table and the curve style\
yes default value False

2025-02-26 16:41 UTC, Ghanshyam-grid commented on pandapower/create.py
> +        **curve_style** (string, None) - The curve style of the generator represents the relationship \
e.g. "straightLineYValues" and "constantYValue"

2025-02-26 16:43 UTC, Ghanshyam-grid commented on pandapower/create.py
> +        **id_q_capability_curve_table** (int, None) - references the index of the characteristic from the lookup table \
e.g. 0, 1, 2, 3

2025-02-26 16:47 UTC, Ghanshyam-grid commented on pandapower/create.py
> +        **curve_dependency_table** (bool, NaN) - True if both the id_q_capability_curve_table and the curve style\
this is list of bool

2025-02-26 16:48 UTC, Ghanshyam-grid commented on pandapower/create.py
> +        **curve_dependency_table** (bool, NaN) - True if both the id_q_capability_curve_table and the curve style\
right

2025-02-26 16:49 UTC, Ghanshyam-grid commented on pandapower/converter/cim/cim2pp/converter_classes/generators/synchronousMachinesCim16.py
> +                syn_gen_df_origin['curve_dependency_table'] = False
yes

2025-02-26 16:50 UTC, panos-xenos commented on pandapower/build_gen.py
> +                              f"characteristic(s) value(s) is(are) None.")
when is this function executed? During load flow? Because here we stop the execution with the userwarning right? Maybe we have to just log a warning that this is happening and explain what happens to these elements --> qlimits are infinite. Also, what happens if there are default q_min / q_max values in the gen/sgen table? Shouldn't these limits be used instead of infinite?

2025-02-26 16:51 UTC, panos-xenos commented on pandapower/build_gen.py
> +                              f"characteristic(s) value(s) is(are) None.")
there is also no need to say "is(are) True". "is True" is enough because it refers to the curve_dependency_table parameter

2025-02-26 16:55 UTC, panos-xenos commented on pandapower/build_gen.py
> +        raise UserWarning(f"One of {element}(s) id characteristic(s) or curve "
sorry, I'm still confused. Here, this user warning is raised under "else:". In this case "else" means len(element_data) == 0 which means there are no elements with curve_dependency_table = True, right?

2025-02-26 16:55 UTC, panos-xenos commented on pandapower/build_gen.py
> +        raise UserWarning(f"One of {element}(s) id characteristic(s) or curve "
also please check also here if this needs to be a userwarning that would stop the execution or it can be a warning log instead?

2025-02-26 16:59 UTC, panos-xenos commented on pandapower/build_gen.py
> +        net[element].loc[element_data.index, ['max_q_mvar', 'min_q_mvar']] = np.column_stack((calc_q_max, calc_q_min))
I think this could be a problem. Probably we need to change the load flow logic to consider the characteristic values instead of the defaults ones if the curve_dependency flag is True. This is what we've also done for trafos and shunts - we don't change the default values, because the user cannot revert back to the original values.

2025-02-26 17:04 UTC, Ghanshyam-grid commented on pandapower/control/util/diagnostic.py
> +            not {"id_q_capability_curve_table", "curve_dependency_table", "curve_style"}.issubset(net[element].columns)
yes it is required. see mismatch variable below this code.

2025-02-26 17:05 UTC, panos-xenos commented on pandapower/build_gen.py
> +                              f"characteristic(s) value(s) is(are) None.")
so if P_setpoint > P_max, then P_setpoint = Pmax and the relevant Qlimits are used, right? I think that makes sense in terms of the logic. However, does p_mw_values dataframe include the right values, i.e. has the check for P_setpoint > P_max or P_setpoint < P_min happened already?

2025-02-26 17:05 UTC, panos-xenos commented on pandapower/build_gen.py
> +                          f"style(s) of {element}(s) is(are) incorrect or not available even if the q_capability_curve_table is available.")
ask chatgpt for advice!

2025-02-26 17:05 UTC, Ghanshyam-grid commented on doc/elements/sgen.rst
> +in net.q_capability_curve_table, thereby associating each static generator with its corresponding capability curve.
I changed only the column name in gen and sgen from id_q_capability_curve_table to id_q_capability_curve_characteristic, because I already have a dataframe with same name called q_capability_curve_characteristic.

2025-02-26 17:06 UTC, panos-xenos commented on pandapower/control/util/auxiliary.py
> +            not {"id_q_capability_curve_table", "curve_dependency_table", "curve_style"}.issubset(net[element].columns)
maybe the documentation has to explain what kind of interpolation we use for each curve style

2025-02-26 17:07 UTC, panos-xenos commented on doc/elements/gen.rst
> +column in net.q_capability_curve_table, associating each generator with its respective capability curve.
please ensure you update all documentation accordingly!

2025-02-26 17:13 UTC, panos-xenos commented on pandapower/create.py
> +        **curve_dependency_table** (bool, NaN) - True if both the id_q_capability_curve_table and the curve style\
I meant to update to **curve_dependency_table** (list of bool, False)

2025-02-26 17:13 UTC, panos-xenos commented on pandapower/create.py
> +        **id_q_capability_curve_table** (int, None) - references the index of the characteristic from the lookup table \
I meant to update to  **id_q_capability_curve_table** (list of ints, None)

2025-02-26 17:14 UTC, panos-xenos commented on pandapower/create.py
> +        **curve_style** (string, None) - The curve style of the generator represents the relationship \
I meant to update to **curve_style** (list of strings, None)

2025-02-26 17:16 UTC, panos-xenos commented on pandapower/create.py
> +        **curve_dependency_table** (bool, NaN) - True if both the id_q_capability_curve_table and the curve style\
then please update everywhere to **curve_dependency_table** (bool, False)

2025-02-26 17:17 UTC, panos-xenos commented on pandapower/create.py
> +
sorry I meant this blank line! Insignificant, sorry!

2025-02-26 17:19 UTC, panos-xenos commented on pandapower/create.py
> +        **curve_dependency_table** (bool, NaN) - True if both the id_q_capability_curve_table and the curve style\
please update to **curve_dependency_table** (bool, False)

2025-02-26 17:21 UTC, panos-xenos commented on pandapower/converter/cim/cim2pp/converter_classes/generators/synchronousMachinesCim16.py
> +                syn_gen_df_origin['curve_dependency_table'] = False
but do all gens have no curve_dependency_table? I'm probably missing something.

2025-02-27 07:56 UTC, Ghanshyam-grid commented on doc/elements/sgen.rst
> +      "constantYValue" and "straightLineYValues".
Instead of providing a link, which may expire in the coming years, I will write a description about it. What do you think?

2025-02-27 08:31 UTC, Ghanshyam-grid commented on pandapower/build_gen.py
> +        raise UserWarning(f"One of {element}(s) id characteristic(s) or curve "
1. Yes, you are right. There is no curve_dependency_table = True, but the q_capability_table and q_capability_characteristics are present. This warning only arises when the capability characteristics are available but not linked.
2. I changed it from a userwarning to a logger warning.

2025-02-28 15:03 UTC, Ghanshyam-grid commented on pandapower/build_gen.py
> +        _calculate_qmin_qmax_from_q_capability_curve_characteristics(net,"gen")
According to CGMES, synchronous machines and equivalent injections have Q capability curve data. 
In pandapower, synchronous machines are converted into gen or sgen, and equivalent injections are converted into ward and xward.

2025-02-28 15:38 UTC, Ghanshyam-grid commented on pandapower/build_gen.py
> +        net[element].loc[element_data.index, ['max_q_mvar', 'min_q_mvar']] = np.column_stack((calc_q_max, calc_q_min))
there is always None value so no need to worry about the original values

2025-02-28 15:41 UTC, Ghanshyam-grid commented on pandapower/build_gen.py
> +                              f"characteristic(s) value(s) is(are) None.")
in that case it takes always maximum possible value of q_min and q_max based on P_max.

2025-02-28 15:43 UTC, Ghanshyam-grid commented on pandapower/control/util/auxiliary.py
> +            not {"id_q_capability_curve_table", "curve_dependency_table", "curve_style"}.issubset(net[element].columns)
Added : Linear interpolation is employed to determine qmin and qmax based on the given active power dispatch for the both curve types.

2025-02-28 16:05 UTC, Ghanshyam-grid commented on pandapower/control/util/diagnostic.py
> +def q_capability_curve_table_diagnostic(net, element):
i changed it from q_capability_curve_table_diagnostic -> q_capability_curve_characteristics_diagnostic

2025-02-28 16:09 UTC, Ghanshyam-grid commented on pandapower/converter/cim/cim2pp/converter_classes/generators/synchronousMachinesCim16.py
> +                syn_gen_df_origin['curve_dependency_table'] = False
I will set curve_dependedency_tabel during creating the characteristics.

2025-02-28 16:13 UTC, Ghanshyam-grid commented on pandapower/create.py
> +        net.q_capability_curve_table
link to q_capability_curve_characteristic

2025-03-04 09:00 UTC, Ghanshyam-grid commented on pandapower/control/util/auxiliary.py
> +def create_q_capability_curve_characteristics_object(net):
add function to build_pp_net.py

2025-03-04 09:30 UTC, Ghanshyam-grid commented on pandapower/control/util/diagnostic.py
> +    # of q_capability_curve_table
Could you please clarify what specific aspects I should review in the q_capability_curve_characteristic? For your information, it is a binary object.

2025-03-04 10:33 UTC, Ghanshyam-grid commented on doc/elements/sgen.rst
> +pandapower.control.util.auxiliary.create_q_capability_curve_characteristics_object can be utilized to automatically
- If the enforce_q_lims option is used with runpp and Q capability data is available, then the create_q_capability_curve_characteristics_object function is invoked to generate the Q capability characteristics and during the load flow they are used. If it is not the case then the default values or the given Q limits are used in the load flow.
- When importing data from CGMES, q_capability_curve_characteristic will be added during the conversion of CGMES to PP.

2025-03-04 10:36 UTC, Ghanshyam-grid commented on doc/elements/gen.rst
> +pandapower.control.util.auxiliary.create_q_capability_curve_characteristics_object can be utilized to automatically
ADD to DOCUMENTATION:

    If the enforce_q_lims option is used with runpp and Q capability data is available, then the create_q_capability_curve_characteristics_object function is invoked to generate the Q capability characteristics and during the load flow they are used. If it is not the case then the default values or the given Q limits are used in the load flow.
    When importing data from CGMES, q_capability_curve_characteristic will be added during the conversion of CGMES to PP.

2025-03-05 10:42 UTC, panos-xenos commented on doc/elements/gen.rst
> +      "constantYValue" and "straightLineYValues".
Let's keep this as unresolved as a reminder for the PF2pp converter implementation

2025-03-05 10:43 UTC, panos-xenos commented on pandapower/build_gen.py
> +        _calculate_qmin_qmax_from_q_capability_curve_characteristics(net,"gen")
agreed to only implement for gen and sgen for now

2025-03-05 11:38 UTC, closed without merging

2025-03-05 14:30 UTC, panos-xenos commented on pandapower/control/util/diagnostic.py
> +    if element not in ["gen", "sgen"]:
not dealing with ext_grid at the moment

2025-03-05 14:43 UTC, panos-xenos commented on pandapower/control/util/diagnostic.py
> +def q_capability_curve_table_diagnostic(net, element):
need to revert back to q_capability_curve_table_diagnostic as discussed